/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplication;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;
/**
 *
 * @author Rutuja
 */
public class EditEmployee extends javax.swing.JFrame {
    ArrayList<Job> jobs;
    ArrayList<Employee> employees;
    DecimalFormat formatter;
    
    
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        
        formatter=new DecimalFormat("#,###.00");
        
        jobs = new ArrayList<Job>();
        employees =new ArrayList<Employee>();
        populateArrayList();
        
        String[] jobsArray=new String[jobs.size()];
        for(int i=0;i<jobs.size();i++)
        {
            jobsArray[i]=jobs.get(i).nameOfJob+" , Rs"+formatter.format(jobs.get(i).getSalary());
        }
        
       ChooseJ.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
       
        String[] empArray=new String[employees.size()];
        for(int i=0;i<employees.size();i++)
        {
            empArray[i]=employees.get(i).getName()+"  "+employees.get(i).getSurname();
        }
        
       ChooseEmp.setModel(new javax.swing.DefaultComboBoxModel<>(empArray));
       ChooseEmp.setSelectedIndex(0);
    }
    
    public void populateArrayList()
    {
        try
        {
            FileInputStream file=new FileInputStream("Jobs.dat");
            ObjectInputStream inputFile=new ObjectInputStream(file);
            
            boolean endOfFile=false;
            while(!endOfFile)
            {
                try
                {
                    jobs.add((Job) inputFile.readObject());
              
                }
                catch(EOFException e)
                {
                     endOfFile=true;
                }
                catch(Exception f)
                {
                     JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try
        {
            FileInputStream file2=new FileInputStream("Employees.dat");
            ObjectInputStream inputFile2=new ObjectInputStream(file2);
            
            boolean endOfFile=false;
            while(!endOfFile)
            {
                try
                {
                    employees.add((Employee) inputFile2.readObject());
              
                }
                catch(EOFException e)
                {
                     endOfFile=true;
                }
                catch(Exception f)
                {
                     JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile2.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
     public void saveEmployeestoFile()
    {
        try
        {
            FileOutputStream file=new FileOutputStream("Employees.dat");
            ObjectOutputStream outputFile=new ObjectOutputStream(file);
            
            for(int i=0;i<employees.size();i++)
            {
                outputFile.writeObject(employees.get(i));
            }
            outputFile.close();
            
             JOptionPane.showMessageDialog(null,"Successfully saved!");
             this.dispose();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
     
      public void saveEmployeestoFileDeleted()
    {
        try
        {
            FileOutputStream file=new FileOutputStream("Employees.dat");
            ObjectOutputStream outputFile=new ObjectOutputStream(file);
            
            for(int i=0;i<employees.size();i++)
            {
                outputFile.writeObject(employees.get(i));
            }
            outputFile.close();
            
             JOptionPane.showMessageDialog(null,"Successfully Deleted!");
             this.dispose();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ChooseEmp = new javax.swing.JComboBox<>();
        Ename = new javax.swing.JTextField();
        Esurname = new javax.swing.JTextField();
        ChooseJ = new javax.swing.JComboBox<>();
        EstaffNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee data");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edit Employee data:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Choose Employee:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 98, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Enter Employee Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 136, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Enter Employee Surname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 174, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Choose Job:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 212, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Enter Employee staff number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        ChooseEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ChooseEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseEmpActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 95, 262, -1));
        getContentPane().add(Ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 133, 262, -1));
        getContentPane().add(Esurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 171, 262, -1));

        ChooseJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ChooseJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseJActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 209, 262, -1));
        getContentPane().add(EstaffNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 262, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapplication/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 321, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapplication/exit.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 321, -1, 57));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myapplication/emplo.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(Ename.getText().isEmpty()||Esurname.getText().isEmpty()||EstaffNo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter all fields");
        }
        else
        {
             int selectedIndex=ChooseEmp.getSelectedIndex();
             employees.get(selectedIndex).setName(Ename.getText().trim());
             employees.get(selectedIndex).setSurname(Esurname.getText().trim());
             employees.get(selectedIndex).setStaffNr(Integer.parseInt(EstaffNo.getText().trim()));
             Job job=jobs.get(ChooseJ.getSelectedIndex());
             employees.get(selectedIndex).setJob(job);
            
            saveEmployeestoFile();
        } 
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedIndex=ChooseEmp.getSelectedIndex();
        
        employees.remove(selectedIndex);
        saveEmployeestoFileDeleted();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ChooseJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseJActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ChooseJActionPerformed

    private void ChooseEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseEmpActionPerformed
        // TODO add your handling code here:
        int selectedIndex=ChooseEmp.getSelectedIndex();
       
        Ename.setText(employees.get(selectedIndex).getName());
        Esurname.setText(employees.get(selectedIndex).getSurname());
        EstaffNo.setText(employees.get(selectedIndex).getStaffNr()+"");
       
        Job job=employees.get(selectedIndex).getJob();
        int index=0;
        
        for(int i=0;i<jobs.size();i++)
        { 

            if(jobs.get(i).equals(job))
            {
               
                index=i;
                break;
            }
        }
         ChooseJ.setSelectedIndex(index);
    }//GEN-LAST:event_ChooseEmpActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChooseEmp;
    private javax.swing.JComboBox<String> ChooseJ;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField EstaffNo;
    private javax.swing.JTextField Esurname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
